server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 👇 이 부분이 핵심입니다! (못 찾으면 index.html로 돌려보냄)
        try_files $uri $uri/ /index.html;
    }
}